python main.py -c ml16.yaml
python main.py -c ml20.yaml
python main.py -c ml2.yaml
python main.py -c ml3.yaml
python main.py -c ml4.yaml
python main.py -c ml8.yaml
python main.py -c momentum.yaml
python main.py -c nesterov.yaml
python main.py -c highway19.yaml
